# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160111_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='nota',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
