# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160111_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='categoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidadeMedida',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadeMedida'),
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidademedida',
            name='descricao',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
