# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160112_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='categoria',
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
        ),
    ]
