# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160112_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='categoria',
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.ManyToManyField(to='app.Categoria'),
        ),
    ]
