# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160112_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Produto'),
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidadeMedida',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidadeMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadeMedida'),
        ),
        migrations.RemoveField(
            model_name='receita',
            name='categoria',
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categoria'),
        ),
        migrations.RemoveField(
            model_name='receita',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ingrediente'),
        ),
    ]
