# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160112_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredienteQuantidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('ingrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ingrediente')),
            ],
        ),
        migrations.AlterField(
            model_name='receita',
            name='ingredientes',
            field=models.ManyToManyField(to='app.IngredienteQuantidade'),
        ),
    ]
