# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_ingrediente_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='ingredientes',
        ),
        migrations.AddField(
            model_name='ingredientequantidade',
            name='receita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Receita'),
        ),
    ]
