# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160112_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidadeMedida',
        ),
        migrations.AddField(
            model_name='ingredientequantidade',
            name='unidadeMedida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UnidadeMedida'),
        ),
    ]
