# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160112_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='rendimento',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
