# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_receita_rendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='produto',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
