# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20160113_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
