# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20160115_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='receita',
        ),
        migrations.AddField(
            model_name='receita',
            name='Ingredientes',
            field=models.ManyToManyField(to='app.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nome',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unidademedida',
            name='descricao',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
