# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20160120_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
