# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20160120_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='Ingredientes',
            new_name='ingredientes',
        ),
    ]
