# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20160120_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
