# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20160122_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='quantidade',
            field=models.FloatField(null=True),
        ),
    ]
